export const tooltipLibrary: Record<string, string> = {
  revenue: "Total recognized sales for the selected period. Formula: Sum of revenue accounts in the GL.",
  "gross-margin": "Portion of revenue retained after direct product costs. Formula: ((Revenue - COGS) / Revenue) * 100.",
  "close-cycle": "Total elapsed days to complete close from period start to final completion. Formula: max(task.completed_at) - min(period_start_date).",
  "on-time": "Share of close tasks finished by assigned due dates. Formula: completed_on_time / total_tasks * 100.",
  "net-cash": "Projected period-end cash after inflows and outflows. Formula: inflows - outflows.",
  "risk-score": "Composite risk score from close, cash, AR, journals, controls, forecast, and pipeline indicators. Formula: weighted_sum(normalized_indicator_scores).",

  open: "Count of close tasks not yet completed. Formula: count(tasks where status != complete).",
  overdue: "Count of close tasks past due date. Formula: count(tasks where completed_at > due_date OR status=overdue).",
  "late-je": "Percent of journal entries posted after cut-off. Formula: late_journals / total_journals * 100.",
  recon: "Percent of reconciliation tasks completed in cycle. Formula: completed_reconciliations / total_reconciliations * 100.",

  dso: "Days Sales Outstanding. Formula: (ending_AR / trailing_3mo_credit_sales) * 90.",
  dpo: "Days Payables Outstanding. Formula: (ending_AP / trailing_3mo_COGS) * 90.",
  ccc: "Cash Conversion Cycle. Formula: DSO + DIO - DPO.",

  "cash-outlook": "Scenario-based cash projection. Formula: recast 13-week ending cash after lever adjustments.",
  "risk-outlook": "Scenario-based close cycle risk outlook. Formula: recast close cycle after staffing/volume assumptions.",
  "margin-outlook": "Scenario-based margin outlook. Formula: (recast_revenue - recast_COGS) / recast_revenue * 100.",

  close: "Close Cycle Overrun Risk means close may finish later than policy due to backlog and pacing. Green <= 7.5 days, Yellow 7.6-9.0, Red > 9.0. Days-to-breach formula: (threshold - current_value) / daily_change_rate.",
  journals: "Late Journal Entry Risk means too many journals are posted after cut-off, increasing rework and control risk. Green <= 8%, Yellow 8.1-12%, Red > 12%. Days-to-breach formula: (threshold - current_value) / daily_change_rate.",
  ar: "AR Collection Slippage means customers are paying slower, which ties up cash and raises DSO. Green <= 45 DSO, Yellow 46-52, Red > 52. Days-to-breach formula: (threshold - current_value) / daily_change_rate.",
  cash: "Cash Runway Compression means available operating cash is shrinking faster than planned. Green >= 10 weeks, Yellow 7-9.9, Red < 7. Days-to-breach formula: (threshold - current_value) / daily_change_rate.",
  controls: "Control exceptions represent unresolved control findings. In KPI context: count(open_control_exceptions). In risk context, Control Exception Aging means issues are open too long, increasing reporting and audit risk (Green <= 12 days, Yellow 12.1-18, Red > 18). Days-to-breach formula: (threshold - current_value) / daily_change_rate.",
  bias: "Forecast Bias Escalation means forecast assumptions are diverging from actuals, reducing planning reliability. Green <= 3%, Yellow 3.1-5%, Red > 5%. Formula: ((forecast - actual) / actual) * 100.",
  shrink: "Inventory Shrink Pressure refers to losses from damage, theft, counting errors, and obsolescence that force margin and reserve adjustments. Green <= 0.8%, Yellow 0.81-1.2%, Red > 1.2%. Formula: (shrink_value / gross_inventory_value) * 100.",
  pipeline: "Pipeline Conversion Gap means expected deal conversion is missing plan, weakening near-term revenue and cash expectations. Green <= 6% miss, Yellow 6.1-10%, Red > 10%. Formula: expected_conversion - realized_conversion.",

  "fan-chart": "Forecast confidence fan chart. Displays baseline forecast and upper/lower confidence bands; wider spread indicates more uncertainty.",
  "trend-line": "12-month actual vs forecast trend line. Tracks top-line trajectory and forecast alignment over time.",
  "close-donut": "Close completion donut. Formula: completed_tasks / total_tasks * 100.",
  "gantt-close": "Close calendar delay chart by owner. Highlights overdue execution pockets by role.",
  "heatmap-delay": "Task-delay heatmap by workstream and owner. Higher values indicate intervention priority.",
  "risk-dial": "Overall DEFCON-style risk dial from weighted indicator severities.",
  "cash-curve": "13-week projected ending cash curve for runway monitoring.",
  "aging-bars": "AR/AP aging by bucket for collection and payment timing quality.",
  waterfall: "Budget to forecast to actual bridge showing movement across reporting states.",
  "variance-decomp": "Variance decomposition by labor, freight, price, mix, and volume drivers.",
  "journal-impact": "Impact of late/manual journal adjustments on reported outcomes.",
  "blockers-table": "Top blockers with aging to prioritize close execution interventions.",
  "customer-cash-risk-table": "Customer concentration cash risk table with exposure and risk band.",
  "data-grid": "Data preview of selected uploaded table with record visibility.",
  "schema-inspector": "Schema inspector listing fields validated in upload mapping.",

  "filter-period": "Period filter controlling time-slice for computed KPIs, risks, and trend visuals.",
  "filter-scenario": "Scenario selector controlling base, stress, or upside output profile.",
  "lever-revenue": "Revenue conversion lever. Adjusts expected win-to-revenue conversion assumptions.",
  "lever-collections": "Collection speed lever. Shifts assumed payment behavior in days.",
  "lever-freight": "Freight inflation lever. Applies logistics cost pressure percentage.",
  "lever-overtime": "Overtime reduction lever. Models labor cost reduction vs throughput tradeoff.",
  "lever-shrink": "Inventory shrink lever. Adjusts shrink assumptions affecting margin and reserves.",
  "lever-hiring": "Hiring freeze toggle. Simulates hiring pause impact on labor spend and close throughput.",
};
